#!/usr/bin/env bash

usage() {
  printf "Usage: $0 FILENAME\n"
  exit 1
}

convert_datetime(){
  declare -A  month=([Jan]=01 [Feb]=02 [Mar]=03 [Apr]=04 [May]=05 [Jun]=06
  [Jul]=07 [Aug]=08 [Sep]=09 [Oct]=10 [Nov]=11 [Dec]=12)

  declare -a datetime=($1)

  printf "${datetime[3]}-${month[${datetime[2]}]}-${datetime[1]}\n"
}

[[ -z $1 ]] && usage
[[ ! -r $1 ]] && usage

while read -r url; do
  while read -r feed; do
    [[ $feed =~ \</item\> ]] && item=false
    [[ $feed =~ \<item\> ]] && item=true

    if [[ $item = true ]]; then
      if [[ $feed =~ \<title\>(.*)\</title\> ]];then
        title=${BASH_REMATCH[1]}
      fi
      if [[ $feed =~ \<pubDate\>.*\ ([0-9]{2})\ ([A-Za-z]{3})\ ([0-9]{4}).*\</pubDate\> ]]; then
        date=$(convert_datetime "${BASH_REMATCH[@]}")
      fi
      if [[ $feed =~ \<link\>(.*)\</link\> ]]; then
        link=${BASH_REMATCH[1]}
      fi
      if [[ ! -z $title && ! -z $date && ! -z $link ]]; then
        items+=("$date $title $link")
        title="";date="";link=""
      fi
    fi
  done < <(curl --silent $url)
done < "$1"

for item in "${items[@]}"; do
    printf "$item\n"
done | sort
